/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef HM2SYSSTATMIB_H
#define HM2SYSSTATMIB_H

#include <syslog.h>

#define SYSLOG_ERR(msg_format, args...) syslog(LOG_ERR, msg_format, ##args )

/* function declarations */
void init_hm2sysstatMIB(void);
Netsnmp_Node_Handler handle_hm2AgentInfodAdminStatus;
Netsnmp_Node_Handler handle_hm2AgentInfodNoConnections;

#endif /* HM2SYSSTATMIB_H */
